### ISSUE TITLE
关于ResNet3D_Pytorch

### ISSUE THREAD

**Issue by zzwei1** [fourierer/Video_Classification_ResNet3D_Pytorch#1]
你好，请问你试过https://github.com/kenshohara/3D-ResNets-PyTorch ./moudles里的resnext吗？我试了一下这个有bug。
另外，你的笔记做的好认真，我最近也在看视频分类、行为识别，感觉看了你总结的很有帮助，感谢，希望以后可以多多交流！

**Comment by fourierer** [comment]
@zzwei1 resnext我试过，确实有问题。感谢关注~
